//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classroom_Client
{
    
    #region Windows Form Designer generated code
    public partial class MainWindow
    {
        private void InitializeComponent()
        {
            this.button1 = new System.Windows.Forms.Button();
            // 
            // button1
            //
            this.button1.BackColor = System.Drawing.Color.Gray;
            this.button1.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.button1.Text = "button1";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Location = new System.Drawing.Point(376, 184);
            this.button1.Name = "button1";
            this.button1.TabIndex = 0;
            // 
            // MainWindow
            // 
            this.BackColor = System.Drawing.Color.Gray;
            this.ClientSize = new System.Drawing.Size(1912, 1053);
            this.Text = "MainWindow";
            this.Controls.Add(this.button1);
            this.Name = "MainWindow";
        }
        private System.Windows.Forms.Button button1;
    }
    #endregion
}
